name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # - name: Spotify
      #   if: ${{ success() || failure() }}
      #   uses: lowlighter/metrics@latest
      #   with:  
      #     filename: spotify.svg
      #     token: ${{ secrets.SPOTIFY_CLIENT_ID }}", "${{ secrets.SPOTIFY_CLIENT_SECRET }}", "${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      #     plugin_music_mode: playlist
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_fortune: yes 
